import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Reader for content/status.json — the build artifact behind /admin/status
 * (scripts/build-status.mjs: content/days.yml joined with what the build
 * actually produced). Holds facts only: cluster ids, slugs, upstream URLs.
 * Never a base-path-prefixed href — the page applies NEXT_PUBLIC_BASE_PATH
 * at render time, same rule as generated MDX.
 */

/** How a worksheet's deck reaches the reader. */
export type Deck =
  /** tex/<slug>/slides.tex compiled and hosted here (`pdf`/`tex` = staged). */
  | { kind: "built"; slug: string; pdf: boolean; tex: boolean }
  /** A prebuilt deck hosted elsewhere — linked out, never served by us. */
  | { kind: "external"; slug?: string; url: string }
  | { kind: "none"; slug?: string };

export type DayModule = {
  slug: string;
  title: string;
  cluster: string | null;
  unlisted: boolean;
  pdf: boolean;
  deck: Deck;
};

/** Where a day's buildable source is. `in-repo` is derived (a worksheet
 *  claimed the day); the rest come from content/days.yml. */
export type SourceKind = "in-repo" | "ready" | "readings" | "partial" | "missing";

export type Day = {
  code: string;
  cluster: string;
  title: string;
  lead: string;
  doc: string;
  /** `kind` is the current truth, `declared` is what days.yml claimed — they
   *  differ once a worksheet claims the day (a ported reading day is both). */
  source: { kind: SourceKind; declared: SourceKind; url: string | null; note: string | null };
  slidesUrl: string | null;
  modules: DayModule[];
  live: boolean;
  slides: { kind: "built" | "external" | "none"; decks: Deck[] };
};

export type Status = {
  /** Generated by a --check run (watch / preview / pre-push): no PDFs were
   *  compiled, so the deck and PDF columns understate reality. */
  checkOnly: boolean;
  days: Day[];
  /** Built modules that claim no day — surfaced, not hidden. */
  unassigned: DayModule[];
  counts: {
    days: number;
    live: number;
    decksBuilt: number;
    decksHosted: number;
    readingDays: number;
    awaitingSource: number;
  };
};

const STATUS_FILE = path.join(process.cwd(), "content", "status.json");

/** null when the content build hasn't run yet (page renders a hint instead). */
export async function readStatus(): Promise<Status | null> {
  try {
    return JSON.parse(await readFile(STATUS_FILE, "utf8")) as Status;
  } catch {
    return null;
  }
}
